### ISSUE TITLE
Uninstall not working for notepad++

### ISSUE THREAD

**Issue by quillypowers** [realslacker/SoftwareInstallDsc#2]
I tried using the below configuration to uninstall any instances of notepad++ using either msi or exe, but both throw the null exception seen below.
SoftwareInstall Notepadpp
            {
                Ensure = "Absent"
                Type   = "exe"
                Name   = "Notepad++*"
            }

#error
VERBOSE: [S150RCMCWEB1-R]: LCM:  [ Start  Resource ]  [[SoftwareInstall]Notepadpp]
VERBOSE: [S150RCMCWEB1-R]: LCM:  [ Start  Test     ]  [[SoftwareInstall]Notepadpp]
VERBOSE: [S150RCMCWEB1-R]:                            [[SoftwareInstall]Notepadpp] Entering Test-TargetResource in file DSC_xSoftwareInstallResource.psm1.
VERBOSE: [S150RCMCWEB1-R]:                            [[SoftwareInstall]Notepadpp] Entering Get-TargetResource in file DSC_xSoftwareInstallResource.psm1.
VERBOSE: [S150RCMCWEB1-R]:                            [[SoftwareInstall]Notepadpp] Searching for products matching 'Notepad++*' with versions matching ANY
VERBOSE: [S150RCMCWEB1-R]:                            [[SoftwareInstall]Notepadpp] Found matching product 'Notepad++ (64-bit x64)' 8.6.2 from publisher Notepad++ Team.
You cannot call a method on a null-valued expression.
At C:\projects\SqlDscGit\DevServers\RunAll\WebApp\ServerConfigs.ps1:2208 char:21
+ ...             Start-DSCConfiguration -Path $localpath -Cimsession $Sess ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : InvokeMethodOnNull
    + PSComputerName        : S150RCMCWEB1-R

**Comment by quillypowers** [comment]
> There was a bug where a missing product ID would cause an error in the resource. I'm pushing a new version to PSGallery.

Thanks!  Pulled and testing soon.

**Comment by realslacker** [comment]
It always tries to pull it from the registry

**Comment by quillypowers** [comment]
Hm.. getting fips errs, it did work though.
VERBOSE: [S150RCMCWEB1-R]:                            [[SoftwareInstall]Notepadpp] Run command line: "C:\Program Files\Notepad++\uninstall.exe" /S
VERBOSE: [S150RCMCWEB1-R]:                            [[SoftwareInstall]Notepadpp] Package uninstall was completed.
VERBOSE: [S150RCMCWEB1-R]: LCM:  [ End    Set      ]  [[SoftwareInstall]Notepadpp]  in 1.3120 seconds.
PowerShell DSC resource DSC_SoftwareInstallResource  failed to execute Set-TargetResource functionality with error message: Exception calling ".ctor" with "0" argument(s): "This implementation is not part of the 
Windows Platform FIPS validated cryptographic algorithms." 

I'll dig in further tomorrow.  Thanks again.

**Comment by realslacker** [comment]
What version of PowerShell are you running DCS under?

- Shannon Graybrook
________________________________

**Comment by quillypowers** [comment]
Sorry 5.1

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  2506

**Comment by realslacker** [comment]
Can you share your DSC configuration block, I can try to reproduce the issue.

**Comment by quillypowers** [comment]
SoftwareInstall Notepadpp
            {
                Ensure = "Absent"
                Type   = "exe"
                Name   = "Notepad++*"
            }
